# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'reactnativefirebase' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for saturn_five_react_app
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'RCTImage',
      'DevSupport',
      # 'Core',
  ]

  # Pods for reactnativefirebase
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios/'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'

  target 'reactnativefirebaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'reactnativefirebase-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactnativefirebase-tvOS

  target 'reactnativefirebase-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
